# This file contains application defaults
# Check docs/configuration.md for more information
#node:
#  db:
#    host:
#    name:
#    password:
#    port:
#    username:
#  port:
#  monitoring:
#    enable:
#    dashboard_polling:
#  web_api:
#    coingecko:
#      base_url:
#      endpoints:
#        get_simple_price_in_usd:
#    hedera:
#      base_url:
#      endpoints:
#        get_hbar_price_in_usd:
#    coin_market_cap:
#      api_key:
#      base_url:
#      endpoints:
#        get_latest_quotes: