ignore:
  - ".github"  # ignore folders and all its contents
  - "build"       # wildcards accepted
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.png"
  - "**/*.md"
  - "**/*.mod"

coverage:
  range: 50..100
    round: down
    precision: 2
  status:
    patch:
      default:
        # basic
        target: 60%
        threshold: 0%
        base: auto
        # advanced
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
        flags:
          - "unit"