# This file contains application defaults
hedera:
    validator:
        db:
            host: 127.0.0.1
            name: hedera_validator
            password: validator_pass
            port: 5432
            username: validator
        port: 5200
    eth:
        node_url: wss://ropsten.infura.io/ws/v3/8b64d65996d24dc0aae2e0c6029e5a9b
        bridge_contract_address: 0x5eD8BBE6462B32B7Be746561918CDA3b9E985B2a
        whbar_contract_address: 0xf5aef41a66be75abe659e80f36c41a290e650488
    mirror_node:
        client_address: hcs.testnet.mirrornode.hedera.com:5600
        api_address: http://testnet.mirrornode.hedera.com/api/v1/
        polling_interval: 5
    client:
        network_type: testnet
        operator:
            account_id: 0.0.99661
            private_key: 302e020100300506032b657004220420fc79b49c62c4637437292814eccd640a6173933c30698ddb41c36c195f0b6629
            eth_private_key: bb9282ba72b55a531fa5e7cc83e92e9055c6905648d673f4d57ad663a317da49
    watcher:
        crypto-transfer:
            accounts:
                - id: 0.0.1894
                  max_retries: 10
        consensus-message:
            topics:
                - id: 0.0.125567
                  max_retries: 10
    handler:
        crypto-transfer:
            topic_id: 0.0.125567
            polling_interval: 5
        consensus-message:
            topic_id: 0.0.125567
            addresses:
                - 0x7BB03D96f9D0e233bfF99eC6aa1c5d035Cd3d1c1
                - 0x4fA67c4ebC625B496eFC85c3ebf757551Da88dED
                - 0x8f35870Df31C5C3b9f7772f3dA20EB580e865AB3
            send_deadline: 300