dbs:
  - host: 127.0.0.1
    name: hedera_validator
    password: validator_pass
    port: 5432
    username: validator
  - host: 127.0.0.1
    name: hedera_validator
    password: validator_pass
    port: 5432
    username: validator
  - host: 127.0.0.1
    name: hedera_validator
    password: validator_pass
    port: 5432
    username: validator
  - host: 127.0.0.1
    name: hedera_validator
    password: validator_pass
    port: 5432
    username: validator
evm:
  80001:
    node_url:
  43113:
    node_url: 
