node:
  database:
    host: 127.0.0.1
    name: hedera_validator
    password: validator_pass
    port: 5432
    username: validator
  clients:
    evm:
    hedera:
      operator:
        account_id:
        private_key:
      network: testnet
      rpc:
#        "127.0.0.1": "0.0.1"
    mirror_node:
      api_address: https://testnet.mirrornode.hedera.com/api/v1/
      client_address: hcs.testnet.mirrornode.hedera.com:5600
      polling_interval: 5
      query_default_limit: 25
      query_max_limit: 100
    coingecko:
      api_address: "https://api.coingecko.com/api/v3/"
    coin_market_cap:
      api_key:
      api_address: "https://pro-api.coinmarketcap.com/v2/cryptocurrency/"
  monitoring:
    enable: false
    dashboard_polling: 15 #in minutes
  log_level: info
  log_format: default # default/gcp
  port: 5200
  validator: true
