{
 "title": "Validator Transfers Dashboard",
 "time": { "from": "now-15s", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Balances in HBAR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Balances in HBAR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "({__name__=~\"fee_account_amount\"})",
     "legendFormat": "Fee Account [{{account_id}}]"
    },
    {
     "expr": "({__name__=~\"account_balance_for_.*\"})",
     "legendFormat": "{{name}} Account [{{account_id}}]"
    }
   ]
  },
  { "title": "HBAR Locked vs Minted", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HBAR Locked vs Minted Fungible",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bridge_account_amount", "legendFormat": "HBAR" },
    {
     "expr": "{__name__=~\"Native_Hedera_Fungible_.*_balance.*\"}",
     "legendFormat": "{{symbol}}"
    },
    {
     "expr": "{__name__=~\"Wrapped_Hedera_Fungible_.*_total_supply.*\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "HBAR Locked vs Minted NonFungible",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bridge_account_amount", "legendFormat": "HBAR" },
    {
     "expr": "{__name__=~\"Native_Hedera_NonFungible_.*_balance.*\"}",
     "legendFormat": "{{symbol}}"
    },
    {
     "expr": "{__name__=~\"Wrapped_Hedera_NonFungible_.*_total_supply.*\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Balance between networks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hedera",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "bridge_account_amount",
       "legendFormat": "Locked Hbars in the Bridge account"
      },
      {
       "expr": "{__name__=~\"Native_Hedera_.*_balance.*\"}",
       "legendFormat": "{{symbol}}"
      },
      {
       "expr": "{__name__=~\"Wrapped_Hedera_.*_total_supply.*\"}",
       "legendFormat": "{{symbol}}"
      }
     ]
    },
    {
     "title": "Ethereum",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "{__name__=~\"Native_Ethereum_.*_balance.*\"}",
       "legendFormat": "{{symbol}}"
      },
      {
       "expr": "{__name__=~\"Wrapped_Ethereum_.*_total_supply.*\"}",
       "legendFormat": "{{symbol}}"
      }
     ]
    },
    {
     "title": "Polygon",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "{__name__=~\"Native_Polygon_.*_balance.*\"}",
       "legendFormat": "{{symbol}}"
      },
      {
       "expr": "{__name__=~\"Wrapped_Polygon_.*_total_supply.*\"}",
       "legendFormat": "{{symbol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Check",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count_validators_alive" }
     ]
    }
   ]
  },
  { "title": "All networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Participation Rate (HCS Signatures)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"validators_participation_rate\"}"
    }
   ]
  },
  {
   "title": "[Success Rate] All Networks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] All Networks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred|user_get_his_tokens)\"}"
    }
   ]
  },
  {
   "title": "[Success Rate] All Networks (without user_get_his_tokens metric)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] All Networks (without user_get_his_tokens metric)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native).*_(majority_reached|fee_transferred)\"}"
    }
   ]
  },
  { "title": "Hedera", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "[Success Rate] Hedera Source Network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] Hedera Source Network ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}"
    }
   ]
  },
  {
   "title": "[Success Rate] Hedera Source Network (without user_get_his_tokens metric)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] Hedera Source Network (without user_get_his_tokens metric)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native)_Hedera.*_(majority_reached|fee_transferred)\"}"
    }
   ]
  },
  { "title": "Polygon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "[Success Rate] Polygon Source Network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] Polygon Source Network ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}"
    }
   ]
  },
  {
   "title": "[Success Rate] Polygon Source Network (without user_get_his_tokens metric)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] Polygon Source Network (without user_get_his_tokens metric) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native)_Polygon.*_(majority_reached|fee_transferred)\"}"
    }
   ]
  },
  { "title": "Ethereum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "[Success Rate] Ethereum Source Network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] Ethereum Source Network ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred|user_get_his_tokens)\"}"
    }
   ]
  },
  {
   "title": "[Success Rate] Ethereum Source Network (without user_get_his_tokens metric)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum({__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred)\"}) by (transaction_id) / count({__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred)\"}) by (transaction_id))) / (count(count({__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred)\"}) by (transaction_id)))) * 100"
    }
   ]
  },
  {
   "title": "[Transfers Status] Ethereum Source Network (without user_get_his_tokens metric)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "{__name__=~\"(Wrapped|Native)_Ethereum.*_(majority_reached|fee_transferred)\"}"
    }
   ]
  }
 ]
}