// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: topic_eth_signature_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicEthSignatureMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceChainId uint64                 `protobuf:"varint,1,opt,name=sourceChainId,proto3" json:"sourceChainId,omitempty"` // ID of the chain from which the user has initiated the bridge transfer
	TargetChainId uint64                 `protobuf:"varint,2,opt,name=targetChainId,proto3" json:"targetChainId,omitempty"` // ID of the chain to which the user wants to bridge
	TransferID    string                 `protobuf:"bytes,3,opt,name=transferID,proto3" json:"transferID,omitempty"`        // (EVM - transaction hash + index of the event in the block) / (Hedera - transaction ID)
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`                  // The asset which will be bridged
	Recipient     string                 `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`          // ID / Address of the receiver
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`                // The amount to transfer
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`          // The signature of the validator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicEthSignatureMessage) Reset() {
	*x = TopicEthSignatureMessage{}
	mi := &file_topic_eth_signature_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicEthSignatureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicEthSignatureMessage) ProtoMessage() {}

func (x *TopicEthSignatureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_topic_eth_signature_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicEthSignatureMessage.ProtoReflect.Descriptor instead.
func (*TopicEthSignatureMessage) Descriptor() ([]byte, []int) {
	return file_topic_eth_signature_message_proto_rawDescGZIP(), []int{0}
}

func (x *TopicEthSignatureMessage) GetSourceChainId() uint64 {
	if x != nil {
		return x.SourceChainId
	}
	return 0
}

func (x *TopicEthSignatureMessage) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

func (x *TopicEthSignatureMessage) GetTransferID() string {
	if x != nil {
		return x.TransferID
	}
	return ""
}

func (x *TopicEthSignatureMessage) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *TopicEthSignatureMessage) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TopicEthSignatureMessage) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TopicEthSignatureMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_topic_eth_signature_message_proto protoreflect.FileDescriptor

const file_topic_eth_signature_message_proto_rawDesc = "" +
	"\n" +
	"!topic_eth_signature_message.proto\x12\x05proto\"\xf0\x01\n" +
	"\x18TopicEthSignatureMessage\x12$\n" +
	"\rsourceChainId\x18\x01 \x01(\x04R\rsourceChainId\x12$\n" +
	"\rtargetChainId\x18\x02 \x01(\x04R\rtargetChainId\x12\x1e\n" +
	"\n" +
	"transferID\x18\x03 \x01(\tR\n" +
	"transferID\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x1c\n" +
	"\trecipient\x18\x05 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignatureB8Z6github.com/limechain/hedera-eth-bridge-validator/protob\x06proto3"

var (
	file_topic_eth_signature_message_proto_rawDescOnce sync.Once
	file_topic_eth_signature_message_proto_rawDescData []byte
)

func file_topic_eth_signature_message_proto_rawDescGZIP() []byte {
	file_topic_eth_signature_message_proto_rawDescOnce.Do(func() {
		file_topic_eth_signature_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topic_eth_signature_message_proto_rawDesc), len(file_topic_eth_signature_message_proto_rawDesc)))
	})
	return file_topic_eth_signature_message_proto_rawDescData
}

var file_topic_eth_signature_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_topic_eth_signature_message_proto_goTypes = []any{
	(*TopicEthSignatureMessage)(nil), // 0: proto.TopicEthSignatureMessage
}
var file_topic_eth_signature_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_topic_eth_signature_message_proto_init() }
func file_topic_eth_signature_message_proto_init() {
	if File_topic_eth_signature_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topic_eth_signature_message_proto_rawDesc), len(file_topic_eth_signature_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topic_eth_signature_message_proto_goTypes,
		DependencyIndexes: file_topic_eth_signature_message_proto_depIdxs,
		MessageInfos:      file_topic_eth_signature_message_proto_msgTypes,
	}.Build()
	File_topic_eth_signature_message_proto = out.File
	file_topic_eth_signature_message_proto_goTypes = nil
	file_topic_eth_signature_message_proto_depIdxs = nil
}
