// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: topic_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*TopicMessage_FungibleSignatureMessage
	//	*TopicMessage_NftSignatureMessage
	Message isTopicMessage_Message `protobuf_oneof:"message"`
}

func (x *TopicMessage) Reset() {
	*x = TopicMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topic_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage) ProtoMessage() {}

func (x *TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_topic_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage.ProtoReflect.Descriptor instead.
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return file_topic_message_proto_rawDescGZIP(), []int{0}
}

func (m *TopicMessage) GetMessage() isTopicMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *TopicMessage) GetFungibleSignatureMessage() *TopicEthSignatureMessage {
	if x, ok := x.GetMessage().(*TopicMessage_FungibleSignatureMessage); ok {
		return x.FungibleSignatureMessage
	}
	return nil
}

func (x *TopicMessage) GetNftSignatureMessage() *TopicEthNftSignatureMessage {
	if x, ok := x.GetMessage().(*TopicMessage_NftSignatureMessage); ok {
		return x.NftSignatureMessage
	}
	return nil
}

type isTopicMessage_Message interface {
	isTopicMessage_Message()
}

type TopicMessage_FungibleSignatureMessage struct {
	FungibleSignatureMessage *TopicEthSignatureMessage `protobuf:"bytes,1,opt,name=fungibleSignatureMessage,proto3,oneof"`
}

type TopicMessage_NftSignatureMessage struct {
	NftSignatureMessage *TopicEthNftSignatureMessage `protobuf:"bytes,2,opt,name=nftSignatureMessage,proto3,oneof"`
}

func (*TopicMessage_FungibleSignatureMessage) isTopicMessage_Message() {}

func (*TopicMessage_NftSignatureMessage) isTopicMessage_Message() {}

var File_topic_message_proto protoreflect.FileDescriptor

var file_topic_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x5f, 0x65, 0x74, 0x68, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x25, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x65, 0x74, 0x68, 0x5f, 0x6e, 0x66, 0x74, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x18, 0x66, 0x75, 0x6e, 0x67, 0x69,
	0x62, 0x6c, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x18, 0x66, 0x75,
	0x6e, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x56, 0x0a, 0x13, 0x6e, 0x66, 0x74, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x45, 0x74, 0x68, 0x4e, 0x66, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x13, 0x6e, 0x66, 0x74, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2f, 0x68, 0x65, 0x64, 0x65, 0x72, 0x61, 0x2d, 0x65, 0x74, 0x68, 0x2d, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_topic_message_proto_rawDescOnce sync.Once
	file_topic_message_proto_rawDescData = file_topic_message_proto_rawDesc
)

func file_topic_message_proto_rawDescGZIP() []byte {
	file_topic_message_proto_rawDescOnce.Do(func() {
		file_topic_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_topic_message_proto_rawDescData)
	})
	return file_topic_message_proto_rawDescData
}

var file_topic_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_topic_message_proto_goTypes = []interface{}{
	(*TopicMessage)(nil),                // 0: proto.TopicMessage
	(*TopicEthSignatureMessage)(nil),    // 1: proto.TopicEthSignatureMessage
	(*TopicEthNftSignatureMessage)(nil), // 2: proto.TopicEthNftSignatureMessage
}
var file_topic_message_proto_depIdxs = []int32{
	1, // 0: proto.TopicMessage.fungibleSignatureMessage:type_name -> proto.TopicEthSignatureMessage
	2, // 1: proto.TopicMessage.nftSignatureMessage:type_name -> proto.TopicEthNftSignatureMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_topic_message_proto_init() }
func file_topic_message_proto_init() {
	if File_topic_message_proto != nil {
		return
	}
	file_topic_eth_signature_message_proto_init()
	file_topic_eth_nft_signature_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_topic_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_topic_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TopicMessage_FungibleSignatureMessage)(nil),
		(*TopicMessage_NftSignatureMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topic_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topic_message_proto_goTypes,
		DependencyIndexes: file_topic_message_proto_depIdxs,
		MessageInfos:      file_topic_message_proto_msgTypes,
	}.Build()
	File_topic_message_proto = out.File
	file_topic_message_proto_rawDesc = nil
	file_topic_message_proto_goTypes = nil
	file_topic_message_proto_depIdxs = nil
}
