// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: topic_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TopicMessage_FungibleSignatureMessage
	Message       isTopicMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMessage) Reset() {
	*x = TopicMessage{}
	mi := &file_topic_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage) ProtoMessage() {}

func (x *TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_topic_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage.ProtoReflect.Descriptor instead.
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return file_topic_message_proto_rawDescGZIP(), []int{0}
}

func (x *TopicMessage) GetMessage() isTopicMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TopicMessage) GetFungibleSignatureMessage() *TopicEthSignatureMessage {
	if x != nil {
		if x, ok := x.Message.(*TopicMessage_FungibleSignatureMessage); ok {
			return x.FungibleSignatureMessage
		}
	}
	return nil
}

type isTopicMessage_Message interface {
	isTopicMessage_Message()
}

type TopicMessage_FungibleSignatureMessage struct {
	FungibleSignatureMessage *TopicEthSignatureMessage `protobuf:"bytes,1,opt,name=fungibleSignatureMessage,proto3,oneof"`
}

func (*TopicMessage_FungibleSignatureMessage) isTopicMessage_Message() {}

var File_topic_message_proto protoreflect.FileDescriptor

const file_topic_message_proto_rawDesc = "" +
	"\n" +
	"\x13topic_message.proto\x12\x05proto\x1a!topic_eth_signature_message.proto\"x\n" +
	"\fTopicMessage\x12]\n" +
	"\x18fungibleSignatureMessage\x18\x01 \x01(\v2\x1f.proto.TopicEthSignatureMessageH\x00R\x18fungibleSignatureMessageB\t\n" +
	"\amessageB8Z6github.com/limechain/hedera-eth-bridge-validator/protob\x06proto3"

var (
	file_topic_message_proto_rawDescOnce sync.Once
	file_topic_message_proto_rawDescData []byte
)

func file_topic_message_proto_rawDescGZIP() []byte {
	file_topic_message_proto_rawDescOnce.Do(func() {
		file_topic_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topic_message_proto_rawDesc), len(file_topic_message_proto_rawDesc)))
	})
	return file_topic_message_proto_rawDescData
}

var file_topic_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_topic_message_proto_goTypes = []any{
	(*TopicMessage)(nil),             // 0: proto.TopicMessage
	(*TopicEthSignatureMessage)(nil), // 1: proto.TopicEthSignatureMessage
}
var file_topic_message_proto_depIdxs = []int32{
	1, // 0: proto.TopicMessage.fungibleSignatureMessage:type_name -> proto.TopicEthSignatureMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_topic_message_proto_init() }
func file_topic_message_proto_init() {
	if File_topic_message_proto != nil {
		return
	}
	file_topic_eth_signature_message_proto_init()
	file_topic_message_proto_msgTypes[0].OneofWrappers = []any{
		(*TopicMessage_FungibleSignatureMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topic_message_proto_rawDesc), len(file_topic_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topic_message_proto_goTypes,
		DependencyIndexes: file_topic_message_proto_depIdxs,
		MessageInfos:      file_topic_message_proto_msgTypes,
	}.Build()
	File_topic_message_proto = out.File
	file_topic_message_proto_goTypes = nil
	file_topic_message_proto_depIdxs = nil
}
