package fees

const (
	INVALID_TRANSFER_AMOUNT = "INVALID_TRANSFER_AMOUNT"
	INVALID_TRANSFER_FEE    = "INVALID_TRANSFER_FEE"
	INVALID_GAS_PRICE       = "INVALID_GAS_PRICE"
	INSANE                  = "INSANE"
	INSUFFICIENT_FEE        = "INSUFFICIENT_FEE"
	RATE_PROVIDER_FAILURE   = "RATE_PROVIDER_FAILURE"
)
