# This file contains application defaults
# Check docs/configuration.md for more information
#node:
#  db:
#    host:
#    name:
#    password:
#    port:
#    username:
#  port:
#  monitoring:
#    enable: true
#    dashboard_polling: 15 #in minutes