#groups:
#  - name: validators
#    rules:
#      - alert: LowValidatorsParticipationRate
#        # Condition for alerting
#        expr: validators_participation_rate < 66.67
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: 'critical'
#        annotations:
#          description: "Participation Rate: {{ $value }} %"
#
#      - alert: LowFeeAccountAmount
#        # Condition for alerting
#        expr: fee_account_amount < 101
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: 'critical'
#        annotations:
#          description: "Fee account amount: {{ $value }} HBAR"
#
#      - alert: LowOperatorAccountAmount
#        # Condition for alerting
#        expr: operator_account_amount < 100
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: 'critical'
#        annotations:
#          description: "Operator account amount: {{ $value }} HBAR"