#groups:
#  - name: account_amounts
#    rules:
#      - alert: LowFeeAccountAmount
#        # Condition for alerting
#        expr: fee_account_amount < 100
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: "minor"
#          group: "account_amounts"
#        annotations:
#          description: "Fee account amount: {{ $value }} HBAR"
#
#      - alert: LowOperatorAccountAmount
#        # Condition for alerting
#        expr: operator_account_amount < 100
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: "minor"
#          group: "account_amounts"
#        annotations:
#          description: "Operator account amount: {{ $value }} HBAR"
#
#  - name: validators
#    rules:
#      - alert: LowValidatorsParticipationRate
#        # Condition for alerting
#        expr: validators_participation_rate < 66.67
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: "critical"
#          group: "validators"
#          repeat_interval: "long"
#        annotations:
#          description: "Participation Rate: {{ $value }} %"
#      # Rules for health checking. Should be set according to validators count
#      - alert: HealthyValidatorsMinor
#        # Condition for alerting
#        expr: count_validators_alive < 3
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: "minor"
#          group: "validators"
#        annotations:
#          description: "Healthy validators: {{ $value }}"
#      - alert: HealthyValidatorsWarning
#        # Condition for alerting
#        expr: count_validators_alive < 2
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: "warning"
#          group: "validators"
#        annotations:
#          description: "Healthy validators: {{ $value }}"
#      - alert: HealthyValidatorsCritical
#        # Condition for alerting
#        expr: count_validators_alive < 1
#        for: 1m
#        # Labels - additional labels to be attached to the alert
#        labels:
#          severity: "critical"
#          group: "validators"
#          repeat_interval: "long"
#        annotations:
#          description: "Healthy validators: {{ $value }}"
