name: Go build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        name: Setup GO Env
        with:
          go-version: '1.20'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build hedera-eth-bridge-validator
        run: go build -o validator cmd/*
      - name: Upload Binary as artifact
        uses: actions/upload-artifact@master
        with:
          name: hedera-eth-bridge-validator
          path: validator
          if-no-files-found: error